spring:
  application:
    name: gateway

  config:
    import: optional:configserver:http://localhost:8071

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

  # added security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:1010/realms/notification-sys


eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
