server:
  port: 8070  # This is the port where the Eureka Server will run

eureka:
  instance:
    hostname: localhost  # The hostname of the Eureka Server (running locally)
  client:
    fetch-registry: false  # Eureka Server does NOT need to fetch the registry (only clients do)
    register-with-eureka: false  # The server does NOT register itself in the registry
    service-url:
      defaultZone: http://localhost:8070/eureka  # The base URL for Eureka clients to register themselves
